
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},e),ca=[],da="./this.program",k=(a,b)=>{throw b;},ea="object"===typeof window,l="function"===typeof importScripts,fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,q="",ha,u,v,fs,w,ia;
if(fa)q=l?require("path").dirname(q)+"/":__dirname+"/",ia=function(){w||(fs=require("fs"),w=require("path"))},ha=function(a,b){ia();a=w.normalize(a);return fs.readFileSync(a,b?null:"utf8")},v=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=function(a,b,c){ia();a=w.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",
function(a){if(!(a instanceof x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=(a,b)=>{if(noExitRuntime||0<ja)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ea||l)l?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ha=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=e.print||console.log.bind(console),y=e.printErr||console.warn.bind(console);aa(e,ba);
ba=null;e.arguments&&(ca=e.arguments);e.thisProgram&&(da=e.thisProgram);e.quit&&(k=e.quit);var z;e.wasmBinary&&(z=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&la("no native wasm support detected");var ma,na=!1;
function oa(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=A(r);B(n,C,p,r)}return p},array:function(n){var p=A(n.length);pa.set(n,p);return p}};a=e["_"+a];var f=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=qa()),f[g]=m(c[g])):f[g]=c[g]}b=a.apply(null,f);b=function(n){0!==h&&ra(h);return n}(b)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function D(a,b){return a?ta(C,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function va(a){var b=ua(a)+1,c=A(b);B(a,pa,c,b);return c}var wa,pa,C,xa,ya,E,za,Aa,F;
function Ba(){var a=ma.buffer;wa=a;e.HEAP8=pa=new Int8Array(a);e.HEAP16=xa=new Int16Array(a);e.HEAP32=E=new Int32Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=ya=new Uint16Array(a);e.HEAPU32=za=new Uint32Array(a);e.HEAPF32=Aa=new Float32Array(a);e.HEAPF64=F=new Float64Array(a)}var Ca,Da=[],Ea=[],Fa=[],Ga=[],Ha=[],ja=0;function Ia(){var a=e.preRun.shift();Da.unshift(a)}var G=0,Ja=null,H=null;e.preloadedImages={};e.preloadedAudios={};
function la(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";y(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ka(){return I.startsWith("data:application/octet-stream;base64,")}var I;I="doom.wasm";if(!Ka()){var La=I;I=e.locateFile?e.locateFile(La,q):q+La}function Ma(){var a=I;try{if(a==I&&z)return new Uint8Array(z);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){la(b)}}
function Na(){if(!z&&(ea||l)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Ma()});if(u)return new Promise(function(a,b){u(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ma()})}
function J(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Ac;"number"===typeof c?void 0===b.$b?K(c)():K(c)(b.$b):c(void 0===b.$b?null:b.$b)}}}var L=[];function K(a){var b=L[a];b||(a>=L.length&&(L.length=a+1),L[a]=b=Ca.get(a));return b}var Oa=0;function Pa(){for(var a=M.length-1;0<=a;--a)Qa(a);M=[];N=[]}var N=[];function Ra(){if(Oa&&Sa.Vb)for(var a=0;a<N.length;++a){var b=N[a];N.splice(a,1);--a;b.Kc.apply(null,b.xc)}}var M=[];
function Qa(a){var b=M[a];b.target.removeEventListener(b.Ob,b.sc,b.Pb);M.splice(a,1)}function O(a){function b(d){++Oa;Sa=a;Ra();a.Rb(d);Ra();--Oa}if(a.Qb)a.sc=b,a.target.addEventListener(a.Ob,b,a.Pb),M.push(a),Ta||(Ga.push(Pa),Ta=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].Ob==a.Ob&&Qa(c--)}function Ua(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Ta,Sa,Va,Wa,P,Xa,Ya,Za,$a,ab=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Q(a){a=2<a?D(a):a;return ab[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function bb(a){return 0>ab.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function cb(a,b,c,d,f,h){Va||(Va=R(256));a={target:Q(a),Ob:h,Qb:d,Rb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Va;B(Ua(g.target),C,n+0,128);B(m,C,n+128,128);K(d)(f,n,b)&&g.preventDefault()},Pb:c};O(a)}
function db(a,b,c,d,f,h){Wa||(Wa=R(176));a={target:Q(a),Vb:!0,Ob:h,Qb:d,Rb:function(g){var m=Wa;F[m>>3]=g.timeStamp;var n=m>>2;E[n+2]=g.location;E[n+3]=g.ctrlKey;E[n+4]=g.shiftKey;E[n+5]=g.altKey;E[n+6]=g.metaKey;E[n+7]=g.repeat;E[n+8]=g.charCode;E[n+9]=g.keyCode;E[n+10]=g.which;B(g.key||"",C,m+44,32);B(g.code||"",C,m+76,32);B(g.char||"",C,m+108,32);B(g.locale||"",C,m+140,32);K(d)(f,m,b)&&g.preventDefault()},Pb:c};O(a)}
function eb(a,b,c){F[a>>3]=b.timeStamp;a>>=2;E[a+2]=b.screenX;E[a+3]=b.screenY;E[a+4]=b.clientX;E[a+5]=b.clientY;E[a+6]=b.ctrlKey;E[a+7]=b.shiftKey;E[a+8]=b.altKey;E[a+9]=b.metaKey;xa[2*a+20]=b.button;xa[2*a+21]=b.buttons;E[a+11]=b.movementX;E[a+12]=b.movementY;c=bb(c);E[a+13]=b.clientX-c.left;E[a+14]=b.clientY-c.top}
function S(a,b,c,d,f,h){P||(P=R(72));a=Q(a);O({target:a,Vb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ob:h,Qb:d,Rb:function(g){g=g||event;eb(P,g,a);K(d)(f,P,b)&&g.preventDefault()},Pb:c})}function T(a,b,c,d,f){Xa||(Xa=R(260));O({target:a,Ob:f,Qb:d,Rb:function(h){h=h||event;var g=Xa,m=document.pointerLockElement||document.bc||document.dc||document.cc;E[g>>2]=!!m;var n=m&&m.id?m.id:"";B(Ua(m),C,g+4,128);B(n,C,g+132,128);K(d)(20,g,b)&&h.preventDefault()},Pb:c})}
function fb(a,b,c,d,f){O({target:a,Ob:f,Qb:d,Rb:function(h){h=h||event;K(d)(38,0,b)&&h.preventDefault()},Pb:c})}
function gb(a,b,c,d){Ya||(Ya=R(36));a=Q(a);O({target:a,Ob:"resize",Qb:d,Rb:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var g=Ya;E[g>>2]=f.detail;E[g+4>>2]=h.clientWidth;E[g+8>>2]=h.clientHeight;E[g+12>>2]=innerWidth;E[g+16>>2]=innerHeight;E[g+20>>2]=outerWidth;E[g+24>>2]=outerHeight;E[g+28>>2]=pageXOffset;E[g+32>>2]=pageYOffset;K(d)(10,g,b)&&f.preventDefault()}}},Pb:c})}
function hb(a,b,c,d,f,h){Za||(Za=R(1696));a=Q(a);O({target:a,Vb:"touchstart"==h||"touchend"==h,Ob:h,Qb:d,Rb:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.hc=m.ic=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.hc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].ic=1;p=Za;F[p>>3]=g.timeStamp;var t=p>>2;E[t+3]=g.ctrlKey;E[t+4]=g.shiftKey;E[t+5]=g.altKey;E[t+6]=g.metaKey;t+=7;var lb=bb(a),mb=0;for(r in n)if(m=
n[r],E[t]=m.identifier,E[t+1]=m.screenX,E[t+2]=m.screenY,E[t+3]=m.clientX,E[t+4]=m.clientY,E[t+5]=m.pageX,E[t+6]=m.pageY,E[t+7]=m.hc,E[t+8]=m.ic,E[t+9]=m.clientX-lb.left,E[t+10]=m.clientY-lb.top,t+=13,31<++mb)break;E[p+8>>2]=mb;K(d)(f,p,b)&&g.preventDefault()},Pb:c})}function ib(a,b,c,d,f,h){a={target:Q(a),Ob:h,Qb:d,Rb:function(g){g=g||event;K(d)(f,0,b)&&g.preventDefault()},Pb:c};O(a)}
function jb(a,b,c,d){$a||($a=R(104));O({target:a,Vb:!0,Ob:"wheel",Qb:d,Rb:function(f){f=f||event;var h=$a;eb(h,f,a);F[h+72>>3]=f.deltaX;F[h+80>>3]=f.deltaY;F[h+88>>3]=f.deltaZ;E[h+96>>2]=f.deltaMode;K(d)(9,h,b)&&f.preventDefault()},Pb:c})}
function kb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,g){b.drawElementsInstancedANGLE(c,d,f,h,g)})}
function nb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ob(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function pb(a){a.Dc=a.getExtension("WEBGL_multi_draw")}
var qb=1,rb=[],U=[],sb=[],V=[],W=[],X=[],tb=[],ub={};function Y(a){vb||(vb=a)}function wb(a){for(var b=qb++,c=a.length;c<b;c++)a[c]=null;return b}function xb(a,b){a.fc||(a.fc=a.getContext,a.getContext=function(d,f){f=a.fc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?yb(c,b):0}function yb(a,b){var c=wb(tb),d={Bc:c,attributes:b,version:b.vc,Zb:a};a.canvas&&(a.canvas.wc=d);tb[c]=d;("undefined"===typeof b.ec||b.ec)&&zb(d);return c}
function zb(a){a||(a=Ab);if(!a.uc){a.uc=!0;var b=a.Zb;kb(b);nb(b);ob(b);b.zc=b.getExtension("EXT_disjoint_timer_query");pb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var vb,Ab,Bb=["default","low-power","high-performance"],Cb=[null,[],[]];function Db(a,b,c,d){for(var f=0;f<a;f++){var h=Z[c](),g=h&&wb(d);h?(h.name=g,d[g]=h):Y(1282);E[b+4*f>>2]=g}}
function Eb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Y(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else Y(1281)}function Fb(a){var b=ua(a)+1,c=R(b);B(a,C,c,b);return c}
function Gb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Hb(a,b,c,d,f){a-=5120;a=1==a?C:4==a?E:6==a?Aa:5==a||28922==a?za:ya;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>h,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}
var Z,Tb={M:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},P:function(a,b,c){a=Q(a);if(!a)return-4;a=bb(a);F[b>>3]=a.width;F[c>>3]=a.height;return 0},Ya:function(a,b,c){C.copyWithin(a,b,b+c)},za:function(a,b){function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Za:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ma.grow(Math.min(2147483648,
d)-wa.byteLength+65535>>>16);Ba();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},S:function(a,b,c,d){cb(a,b,c,d,12,"blur");return 0},G:function(a,b,c){a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:function(a,b,c,d){cb(a,b,c,d,13,"focus");return 0},aa:function(a,b,c,d){db(a,b,c,d,2,"keydown");return 0},_:function(a,b,c,d){db(a,b,c,d,1,"keypress");return 0},$:function(a,b,c,d){db(a,b,c,d,3,"keyup");return 0},ga:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},da:function(a,
b,c,d){S(a,b,c,d,33,"mouseenter");return 0},ca:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},ea:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},fa:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},V:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.bc||document.body.dc||document.body.cc))return-1;a=Q(a);if(!a)return-4;T(a,b,c,d,"pointerlockchange");T(a,b,c,d,"mozpointerlockchange");T(a,b,c,d,"webkitpointerlockchange");T(a,b,c,d,"mspointerlockchange");
return 0},U:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.bc||document.body.dc||document.body.cc))return-1;a=Q(a);if(!a)return-4;fb(a,b,c,d,"pointerlockerror");fb(a,b,c,d,"mozpointerlockerror");fb(a,b,c,d,"webkitpointerlockerror");fb(a,b,c,d,"mspointerlockerror");return 0},Ja:function(a,b,c,d){gb(a,b,c,d);return 0},W:function(a,b,c,d){hb(a,b,c,d,25,"touchcancel");return 0},X:function(a,b,c,d){hb(a,b,c,d,23,"touchend");return 0},Y:function(a,b,c,d){hb(a,b,c,d,24,
"touchmove");return 0},Z:function(a,b,c,d){hb(a,b,c,d,22,"touchstart");return 0},R:function(a,b,c,d){ib(a,b,c,d,31,"webglcontextlost");return 0},Q:function(a,b,c,d){ib(a,b,c,d,32,"webglcontextrestored");return 0},ba:function(a,b,c,d){a=Q(a);return"undefined"!==typeof a.onwheel?(jb(a,b,c,d),0):-1},na:function(a,b){b>>=2;b={alpha:!!E[b],depth:!!E[b+1],stencil:!!E[b+2],antialias:!!E[b+3],premultipliedAlpha:!!E[b+4],preserveDrawingBuffer:!!E[b+5],powerPreference:Bb[E[b+6]],failIfMajorPerformanceCaveat:!!E[b+
7],vc:E[b+8],Cc:E[b+9],ec:E[b+10],tc:E[b+11],Ec:E[b+12],Fc:E[b+13]};a=Q(a);return!a||b.tc?0:xb(a,b)},ab:function(a,b){a=tb[a];b=D(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&kb(Z);"OES_vertex_array_object"==b&&nb(Z);"WEBGL_draw_buffers"==b&&ob(Z);"WEBGL_multi_draw"==b&&pb(Z);return!!a.Zb.getExtension(b)},ta:function(a){a>>=2;for(var b=0;14>b;++b)E[a+b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},kb:function(a){Ab=tb[a];e.yc=Z=Ab&&Ab.Zb;return!a||Z?0:-5},rb:function(a){Ib(a)},
_a:function(){return 0},Xa:function(){},$a:function(a,b,c,d){for(var f=0,h=0;h<c;h++){var g=E[b>>2],m=E[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=C[g+n],r=Cb[a];0===p||10===p?((1===a?ka:y)(ta(r,0)),r.length=0):r.push(p)}f+=m}E[d>>2]=f;return 0},b:function(a){Z.activeTexture(a)},E:function(a,b){Z.attachShader(U[a],X[b])},c:function(a,b){Z.bindBuffer(a,rb[b])},e:function(a,b){Z.bindFramebuffer(a,sb[b])},Da:function(a,b){Z.bindRenderbuffer(a,V[b])},a:function(a,b){Z.bindTexture(a,W[b])},J:function(a,b,
c,d){Z.blendColor(a,b,c,d)},K:function(a,b){Z.blendEquationSeparate(a,b)},L:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},Fa:function(a,b,c,d){Z.bufferData(a,c?C.subarray(c,c+b):b,d)},q:function(a,b,c,d){Z.bufferSubData(a,b,C.subarray(d,d+c))},l:function(a){return Z.checkFramebufferStatus(a)},nb:function(a){Z.clear(a)},pb:function(a,b,c,d){Z.clearColor(a,b,c,d)},la:function(a){Z.clearDepth(a)},ob:function(a){Z.clearStencil(a)},n:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},ra:function(a){Z.compileShader(X[a])},
Aa:function(a,b,c,d,f,h,g,m){Z.compressedTexImage2D(a,b,c,d,f,h,m?C.subarray(m,m+g):null)},xa:function(){var a=wb(U),b=Z.createProgram();b.name=a;b.Yb=b.Wb=b.Xb=0;b.ac=1;U[a]=b;return a},ua:function(a){var b=wb(X);X[b]=Z.createShader(a);return b},F:function(a){Z.cullFace(a)},La:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=rb[d];f&&(Z.deleteBuffer(f),f.name=0,rb[d]=null)}},k:function(a,b){for(var c=0;c<a;++c){var d=E[b+4*c>>2],f=sb[d];f&&(Z.deleteFramebuffer(f),f.name=0,sb[d]=null)}},y:function(a){if(a){var b=
U[a];b?(Z.deleteProgram(b),b.name=0,U[a]=null):Y(1281)}},O:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=V[d];f&&(Z.deleteRenderbuffer(f),f.name=0,V[d]=null)}},u:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},Ka:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=W[d];f&&(Z.deleteTexture(f),f.name=0,W[d]=null)}},x:function(a){Z.depthFunc(a)},w:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},N:function(a){Z.disableVertexAttribArray(a)},fb:function(a,b,
c){Z.drawArrays(a,b,c)},gb:function(a,b,c,d){Z.drawArraysInstanced(a,b,c,d)},hb:function(a,b,c,d){Z.drawElements(a,b,c,d)},ib:function(a,b,c,d,f){Z.drawElementsInstanced(a,b,c,d,f)},h:function(a){Z.enable(a)},jb:function(a){Z.enableVertexAttribArray(a)},j:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,V[d])},g:function(a,b,c,d,f){Z.framebufferTexture2D(a,b,c,W[d],f)},H:function(a){Z.frontFace(a)},Ga:function(a,b){Db(a,b,"createBuffer",rb)},m:function(a,b){Db(a,b,"createFramebuffer",sb)},Ea:function(a,
b){Db(a,b,"createRenderbuffer",V)},Ba:function(a,b){Db(a,b,"createTexture",W)},pa:function(a,b){return Z.getAttribLocation(U[a],D(b))},f:function(a,b){Eb(a,b)},va:function(a,b,c,d){a=Z.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>2]=b)},D:function(a,b,c){if(c)if(a>=qb)Y(1281);else if(a=U[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.Yb)for(b=0;b<Z.getProgramParameter(a,35718);++b)a.Yb=Math.max(a.Yb,
Z.getActiveUniform(a,b).name.length+1);E[c>>2]=a.Yb}else if(35722==b){if(!a.Wb)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.Wb=Math.max(a.Wb,Z.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.Wb}else if(35381==b){if(!a.Xb)for(b=0;b<Z.getProgramParameter(a,35382);++b)a.Xb=Math.max(a.Xb,Z.getActiveUniformBlockName(a,b).length+1);E[c>>2]=a.Xb}else E[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},qa:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,C,d,b):0;c&&(E[c>>
2]=b)},B:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Ma:function(a){var b=ub[a];if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Fb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=b&&Fb(b);break;case 7938:b=Fb("OpenGL ES 2.0 ("+
Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Fb(b);break;default:Y(1280)}ub[a]=b}return b},p:function(a,b){b=D(b);if(a=U[a]){var c=a,d=c.Ub,f=c.qc,h;if(!d)for(c.Ub=d={},c.pc={},h=0;h<Z.getProgramParameter(c,35718);++h){var g=Z.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Gb(m);n=0<n?m.slice(0,n):m;var p=c.ac;c.ac+=g;f[n]=[g,p];for(m=
0;m<g;++m)d[p]=m,c.pc[p++]=n}c=a.Ub;d=0;f=b;h=Gb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.qc[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},wa:function(a){a=U[a];Z.linkProgram(a);a.Ub=0;a.qc={}},I:function(a,b){Z.polygonOffset(a,b)},Ca:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},qb:function(a,b,c,d){Z.scissor(a,b,c,d)},sa:function(a,b,c,d){for(var f="",h=0;h<b;++h){var g=d?E[d+4*h>>2]:-1;f+=D(E[c+4*h>>2],0>g?void 0:g)}Z.shaderSource(X[a],
f)},Ia:function(a,b,c){Z.stencilFunc(a,b,c)},ka:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},v:function(a){Z.stencilMask(a)},Ha:function(a,b,c){Z.stencilOp(a,b,c)},ja:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},ya:function(a,b,c,d,f,h,g,m,n){Z.texImage2D(a,b,c,d,f,h,g,m,n?Hb(m,g,d,f,n):null)},i:function(a,b,c){Z.texParameteri(a,b,c)},eb:function(a,b,c,d,f,h,g,m,n){var p=null;n&&(p=Hb(m,g,f,h,n));Z.texSubImage2D(a,b,c,d,f,h,g,m,p)},C:function(a,b){var c=Z,d=c.uniform1i;var f=Z.rc;if(f){var h=
f.Ub[a];"number"===typeof h&&(f.Ub[a]=h=Z.getUniformLocation(f,f.pc[a]+(0<h?"["+h+"]":"")));a=h}else Y(1282),a=void 0;d.call(c,a,b)},o:function(a){a=U[a];Z.useProgram(a);Z.rc=a},lb:function(a,b){Z.vertexAttribDivisor(a,b)},mb:function(a,b,c,d,f,h){Z.vertexAttribPointer(a,b,c,!!d,f,h)},ma:function(a,b,c,d){Z.viewport(a,b,c,d)},Va:function(){e.jc=function(a){0!=Jb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.jc)},Ua:function(){e.oc=function(a){a=a.clipboardData.getData("text");
oa("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.oc)},Ta:function(a){e.Hc=[];a=D(a);a=document.getElementById(a);e.kc=function(b){b.stopPropagation();b.preventDefault()};e.lc=function(b){b.stopPropagation();b.preventDefault()};e.mc=function(b){b.stopPropagation();b.preventDefault()};e.nc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.Ic=c;Kb(c.length);var d;for(d=0;d<c.length;d++)oa("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Lb(b.clientX,
b.clientY)};a.addEventListener("dragenter",e.kc,!1);a.addEventListener("dragleave",e.lc,!1);a.addEventListener("dragover",e.mc,!1);a.addEventListener("drop",e.nc,!1)},Oa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},t:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Mb()});document.body.append(a)},Pa:function(){document.exitPointerLock&&document.exitPointerLock()},
s:function(){document.getElementById("_sokol_app_input_element").focus()},Wa:function(a){a=D(a);e.Tb=document.getElementById(a);e.Tb||console.log("sokol_app.h: invalid target:"+a);e.Tb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Sa:function(){window.removeEventListener("beforeunload",e.jc)},Ra:function(){window.removeEventListener("paste",e.oc)},Qa:function(a){a=D(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.kc);a.removeEventListener("dragleave",
e.lc);a.removeEventListener("dragover",e.mc);a.removeEventListener("drop",e.nc)},z:function(){e.Tb&&e.Tb.requestPointerLock&&e.Tb.requestPointerLock()},Na:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(C.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},r:function(){document.getElementById("_sokol_app_input_element").blur()},
bb:function(){return e.Sb?e.Sb.bufferSize:0},db:function(a,b,c){e.Nb=null;e.Sb=null;"undefined"!==typeof AudioContext?e.Nb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?e.Nb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Nb=null,console.log("sokol_audio.h: no WebAudio support"));return e.Nb?(console.log("sokol_audio.h: sample rate ",e.Nb.sampleRate),e.Sb=e.Nb.createScriptProcessor(c,0,b),e.Sb.onaudioprocess=function(d){var f=
d.outputBuffer.length,h=Nb(f);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=Aa[(h>>2)+(g*p+m)]},e.Sb.connect(e.Nb.destination),a=function(){e.Nb&&"suspended"===e.Nb.state&&e.Nb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},cb:function(){return e.Nb?e.Nb.sampleRate:0},ha:function(){null!==e.Nb&&(e.Sb&&e.Sb.disconnect(),
e.Nb.close(),e.Nb=null,e.Sb=null)},A:function(a,b,c,d,f,h){b=D(b);var g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";var m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var n=new Uint8Array(g.response),p=n.length;p<=h?(C.set(n,f),Ob(a,d,p)):Pb(a)}else Qb(a,this.status)};g.send()},ia:function(a,b){b=D(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=
function(){if(this.readyState==this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");Rb(a,d)}else Qb(a,this.status)};c.send()},oa:function(a){if(fa){if(!a)return 1;a=D(a);if(!a.length)return 0;a=require("child_process").Jc(a,[],{Gc:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15}return 2})(a.signal)):
a.status<<8|0}if(!a)return 0;E[Sb()>>2]=52;return-1}};
(function(){function a(f){e.asm=f.exports;ma=e.asm.sb;Ba();Ca=e.asm.Mb;Ea.unshift(e.asm.tb);G--;e.monitorRunDependencies&&e.monitorRunDependencies(G);0==G&&(null!==Ja&&(clearInterval(Ja),Ja=null),H&&(f=H,H=null,f()))}function b(f){a(f.instance)}function c(f){return Na().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(f,function(h){y("failed to asynchronously prepare wasm: "+h);la(h)})}var d={a:Tb};G++;e.monitorRunDependencies&&e.monitorRunDependencies(G);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||I.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.tb).apply(null,arguments)};var R=e._malloc=function(){return(R=e._malloc=e.asm.ub).apply(null,arguments)},Mb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Mb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.vb).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.wb).apply(null,arguments)};
var Jb=e.__sapp_html5_get_ask_leave_site=function(){return(Jb=e.__sapp_html5_get_ask_leave_site=e.asm.xb).apply(null,arguments)},Kb=e.__sapp_emsc_begin_drop=function(){return(Kb=e.__sapp_emsc_begin_drop=e.asm.yb).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.zb).apply(null,arguments)};var Lb=e.__sapp_emsc_end_drop=function(){return(Lb=e.__sapp_emsc_end_drop=e.asm.Ab).apply(null,arguments)};
e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.Bb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.Cb).apply(null,arguments)};
var Rb=e.__sfetch_emsc_head_response=function(){return(Rb=e.__sfetch_emsc_head_response=e.asm.Db).apply(null,arguments)},Ob=e.__sfetch_emsc_get_response=function(){return(Ob=e.__sfetch_emsc_get_response=e.asm.Eb).apply(null,arguments)},Qb=e.__sfetch_emsc_failed_http_status=function(){return(Qb=e.__sfetch_emsc_failed_http_status=e.asm.Fb).apply(null,arguments)},Pb=e.__sfetch_emsc_failed_buffer_too_small=function(){return(Pb=e.__sfetch_emsc_failed_buffer_too_small=e.asm.Gb).apply(null,arguments)},Nb=
e.__saudio_emsc_pull=function(){return(Nb=e.__saudio_emsc_pull=e.asm.Hb).apply(null,arguments)},Sb=e.___errno_location=function(){return(Sb=e.___errno_location=e.asm.Ib).apply(null,arguments)},qa=e.stackSave=function(){return(qa=e.stackSave=e.asm.Jb).apply(null,arguments)},ra=e.stackRestore=function(){return(ra=e.stackRestore=e.asm.Kb).apply(null,arguments)},A=e.stackAlloc=function(){return(A=e.stackAlloc=e.asm.Lb).apply(null,arguments)},Ub;
function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}H=function Vb(){Ub||Wb();Ub||(H=Vb)};
function Wb(a){function b(){if(!Ub&&(Ub=!0,e.calledRun=!0,!na)){J(Ea);J(Fa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Xb){var c=a,d=e._main;c=c||[];var f=c.length+1,h=A(4*(f+1));E[h>>2]=va(da);for(var g=1;g<f;g++)E[(h>>2)+g]=va(c[g-1]);E[(h>>2)+f]=0;try{var m=d(f,h);Ib(m)}catch(n){n instanceof x||"unwind"==n||k(1,n)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Ha.unshift(c);J(Ha)}}a=a||ca;if(!(0<G)){if(e.preRun)for("function"==
typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ia();J(Da);0<G||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Wb;function Ib(a){if(!(noExitRuntime||0<ja)){if(e.onExit)e.onExit(a);na=!0}k(a,new x(a))}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Xb=!0;e.noInitialRun&&(Xb=!1);Wb();
